[package]
name = "celestia"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.18", features = ["derive"] }
digest = "0.10.7"
plonky2 = { git = "https://github.com/mir-protocol/plonky2.git" }
plonky2_gadgets = { git = "ssh://git@github.com/succinctlabs/plonky2-gadgets.git" }
rand = "0.8.5"
serde_json = "1.0.103"
sha2 = "0.10.7"
subtle-encoding = "0.5.1"
