name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:  
  test:
    name: CI Test Suite
    runs-on: buildjet-32vcpu-ubuntu-2204
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Add SSH key
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.TENDERMINTX_DEPLOY_KEY }}"
            git config --global --add url."git@github.com:succinctlabs/tendermintx".insteadOf "https://github.com/succinctlabs/tendermintx"
      - run: GIT_SSH_COMMAND="ssh -v" git clone git@github.com:succinctlabs/tendermintx.git

      - uses: actions/checkout@v3
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          submodules: recursive

      - name: rust-cache
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: test-rust-nightly-2023-08-24-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2023-08-24-

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-08-24
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --features "ci" 
        env:
          RUST_LOG: 1
          RUST_BACKTRACE: 1

  lints:
    name: Formatting & Clippy
    runs-on: buildjet-32vcpu-ubuntu-2204
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.TENDERMINTX_DEPLOY_KEY }}
 
      - name: rust-cache
        uses: buildjet/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            ~/.rustup/
          key: clippy-rust-nightly-2023-08-24-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: rust-nightly-2023-08-24-

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2023-08-24
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1